### ISSUE TITLE
when forward , why plus 2  instead of 1 please? 

### ISSUE THREAD

**Issue by videni** [bwaidelich/relay-pagination#1]
can you explain paginate forward, why plus 2 instead of 1 please?

https://github.com/bwaidelich/relay-pagination/blob/a715161783eb0f1f1d98ee4b1be8dc7c6c89e89b/src/Paginator.php#L86

**Comment by videni** [comment]
Never mind , I figured it out. The follow pseudo code is what I try to understand it.  it is different between after cursor is null and zero. so I evaluate all these cases.

##  after == null

```
offset:  0, 1, 2, 3
element: A, B, C, D
```

after = null;
first = 2

which means we want:  A， B.

turn cursor to offset and limit ,  then,

```
offset = after ; // got null, zero in database
limit = first + 1 + 1;  //got 4 , check the following for why add double 1.
```

all_edges = [A,B,C,D]
since after is null, no skip first
has_previous_page = false;
since all_edges.len() > first
has_next_page = true;
final_edges = slice(all_edges, 0, first) //got [A, B]

this works correct.

## after == 0

```
offset:  0, 1, 2, 3, 4
element: A, B, C, D, E
```

after = 0;
first = 2

which means, we want [B, C] after A, then turn cursor to offset and limit, we got
```
offset = after; // 0,since we want  [B, C] after A, we must another 1 to limit.
limit = first + 1 + 1; // 1 for checking if next page exists, another 1 for if previous page exists.
```

all_edges = [A, B,C,D ]

since after != null
has_previous_page =true;
final_edges = all_edges `skip first` // got [B, C, D] 

since final_edges.len() > first:
has_next_page =true;

final_edges = slice(final_edges, 0, first) // got [B, C]


Colusion: `correct`


## after == 1

```
offset:  0, 1, 2, 3, 4, 5, 6
element: A, B, C, D, E, F, G
```

after = 1
first = 2 

which means, we want [C, D] after B.  then turn cursor to offset and limit, we got

```
offset = after ;// got 1
limit = first + 1 + 1; //4 
```

all_edges = [B, C, D, E]

since after != null:
has_previous_page =true; // also all_edges not empty
final_edges =  all_edges `skip first`  // got [C, D, E]

since final_edges.len() > first:
has_next_page = true;
final_edges = slice(final_edges, 0, first) // got [C, D]

got final edges = [C, D]


Colusion: `correct`

**Comment by bwaidelich** [comment]
Hey,
thanks for your feedback and the thorough explanation, that will surely help others who stumble upon the same weirdness (including me, who had to think about it again). You're correct, we'll need to fetch (at most) two additional edges in order to populate `PageInfo.hasPreviousPage` _and_ `PageInfo.hasNextPage`
